nsf:
    image: erichough/nfs-server
    container_name: nfs
    restart: unless-stopped
    cap_add:
        - SYS_ADMIN
    security_opt:
        - apparmor=erichough-nfs
    volumes:
        - /mnt/data/:/exported/data
        - ./config/exports:/etc/exports:ro
    ports:
        - "111:111"
        - "111:111/udp"
        - "32765:32765"
        - "32765:32765/udp"
        - "32767:32767"
        - "32767:32767/udp"
        - "2049:2049"
        - "2049:2049/udp"