version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/conf:/mosquitto/config
      - ../caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mqtt.armriot.com:/certificates:ro
    ports:
      - 8883:8883

