jupyter:
  image: jupyter/datascience-notebook:latest
  user: root
  volumes:
    - ./data:/home/jovyan/
  ports:
    - 8888:8888
  restart: unless-stopped
  command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
  environment:
    JUPYTER_ENABLE_LAB: "yes"
    JUPYTER_TOKEN: "112"
