services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/config.json:/config.json
    command: --interval 30 --label-enable --cleanup
    restart: unless-stopped
